<?php

	$resp_code = array(
		'ERR_NOSUCHNICK' => '401',
		'ERR_NOSUCHSERVER' => '402',
		'ERR_NOSUCHCHANNEL' => '403',
		'ERR_CANNOTSENDTOCHAN' => '404',
		'ERR_TOOMANYCHANNELS' => '405',
		'ERR_WASNOSUCHNICK' => '406',
		'ERR_TOOMANYTARGETS' => '407',
	);